{
 "title": "Confluent Cloud KSQL",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ksql_id",
    "label": "KSQL ID",
    "query": {
     "query": "label_values(confluent_kafka_ksql_query_saturation, ksql_id)"
    }
   },
   {
    "name": "query_id",
    "label": "Query ID",
    "query": {
     "query": "label_values(confluent_kafka_ksql_query_saturation, query_id)"
    }
   },
   {
    "name": "task_id",
    "label": "Task ID",
    "query": {
     "query": "label_values(confluent_kafka_ksql_task_stored_bytes, task_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ksqlDB streaming unit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_streaming_unit_count",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  {
   "title": "Total ksqlDB application count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_streaming_unit_count)"
    }
   ]
  },
  {
   "title": "ksqlDB query count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(confluent_kafka_ksql_query_saturation{ksql_id=~\"$ksql_id\"})"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "description": "Query IDs for all persistent queries in a cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "confluent_kafka_ksql_query_saturation{ksql_id=\"$ksql_id\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Query Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (query_id, ksql_id) (confluent_kafka_ksql_query_saturation{query_id=~\"$query_id\", ksql_id=~\"$ksql_id\"}*100)",
     "legendFormat": "{{ksql_id}}-{{query_id}}"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (ksql_id) (confluent_kafka_ksql_storage_utilization{ksql_id=~\"$ksql_id\"}*100)",
     "legendFormat": "{{ksql_id}}"
    }
   ]
  },
  {
   "title": "Task Stored Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (query_id, ksql_id, task_id) (confluent_kafka_ksql_task_stored_bytes{query_id=~\"$query_id\", ksql_id=~\"$ksql_id\", task_id=~\"$task_id\"}*100)",
     "legendFormat": "{{ksql_id}}-{{query_id}}-{{task_id}}"
    }
   ]
  }
 ]
}